#!/bin/bash
# git info in prompt

git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

docker_machine_prompt() {
  if [ -n "$DOCKER_MACHINE_NAME" ]; then
    echo "[$DOCKER_MACHINE_NAME]"
  fi
}

if [ "$color_prompt" = yes ]; then
  PS1="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\[\033[01;33m\]\$(__git_ps1) \[\033[00;31m\]\$(docker_machine_prompt)\[\e[0m\]$ "
else
  PS1="${debian_chroot:+($debian_chroot)}\u@\h:\w\$(git_branch) \$(docker_machine_prompt)$ "
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
  xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
  *)
    ;;
esac
